name: Deploy to Server

on:
  push:
    branches: [ "main" ]  # Запускать только при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/coincidence
            git pull origin main
            docker-compose down
            docker-compose up --build -d
            echo "✅ Deployment completed!"